"""add audit fields to user

Revision ID: a5ac2a5246f5
Revises: 95b3b8424d69
Create Date: 2025-07-06 19:31:13.096372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5ac2a5246f5'
down_revision: Union[str, Sequence[str], None] = '95b3b8424d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(), nullable=True))
    op.alter_column('users', 'rol',
               existing_type=postgresql.ENUM('ADMIN', 'DOCENTE', 'ALUMNO', 'INVITADO', name='rolusuario'),
               type_=sa.Enum('ADMIN', 'DOCENTE', 'ALUMNO', 'INVITADO', name='rolusuario', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'rol',
               existing_type=sa.Enum('ADMIN', 'DOCENTE', 'ALUMNO', 'INVITADO', name='rolusuario', native_enum=False),
               type_=postgresql.ENUM('ADMIN', 'DOCENTE', 'ALUMNO', 'INVITADO', name='rolusuario'),
               existing_nullable=False)
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
