"""add login attempt tracking fields to user

Revision ID: a71cd5418957
Revises: 9672b844fcae
Create Date: 2025-07-06 20:26:08.110367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71cd5418957'
down_revision: Union[str, Sequence[str], None] = '9672b844fcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_login')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
