name: Run Tests & Upload Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print debug variables
        run: |
          echo "ACTIONS_RUNNER_DEBUG=$ACTIONS_RUNNER_DEBUG"
          echo "ACTIONS_STEP_DEBUG=$ACTIONS_STEP_DEBUG"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=app tests/ --cov-report=xml

          - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
