name: Run Tests & Upload Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: echo "DATABASE_URL=sqlite+aiosqlite:///:memory:" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=secretfortests" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite+aiosqlite:///:memory:" >> $GITHUB_ENV
          echo "MAIL_USERNAME=test@example.com" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=password123" >> $GITHUB_ENV
          echo "MAIL_FROM=test@example.com" >> $GITHUB_ENV
          echo "MAIL_PORT=587" >> $GITHUB_ENV
          echo "MAIL_SERVER=smtp.test.com" >> $GITHUB_ENV
          echo "MAIL_TLS=true" >> $GITHUB_ENV
          echo "MAIL_SSL=false" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
